[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "muscles"
version = "1.0.0rc3"
description = "Muscles framework core"
readme = "README.md"
authors = ["Denis B. <denis@butko.info>"]
license = "MIT"
packages = [{include = "muscles", from = "src"}]


[tool.poetry.dependencies]
python = "^3.9"
watchdog = "^4.0.0"
dnspython = "==2.6.1"
pyyaml = "~=6.0.0"
setuptools = "==69.0.2"
greenlet = "==3.0.2"
jsonschema = "==4.16.0"


[tool.poetry.dev-dependencies]
pytest = "==7.1.3"
